version: '3.8'
services:
  mysql:
    image: mysql:8.0.32
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
